#!/usr/bin/env python
#coding=utf-8
import time
import calendar
import sys
import os


#函数
def printMethod(str) :
    print "打印任何输入的字符串"
    print str;
    return;
#time
print time.time();
print time.strftime('%Y-%m-%d %H:%M:%S',time.localtime()); 

localtime = time.localtime();
print localtime.tm_year;

print time.asctime(time.localtime(time.time()));

#calendar
print calendar.month(2016,1)

time.sleep(1);

print "======sleep end======"
#系统相关信息模块
print "sys begin: please input readText:"
#readText = sys.stdin.readline()
#print readText
#print sys.platform

#操作系统相关的调用和操作
print "HOME PATH :", os.environ['HOME']
print "OS LOGIN USER NAME: ",os.environ['LOGNAME']
print os.getenv

#内置function
localGolbal = globals();
print localGolbal

localList=['levom','sober','fd323']
#localDict = dict(localList)
print tuple(localList)

printMethod("testFunction")

